version: "3.9"

services:
  db:
    image: postgres:15
    container_name: workhub-postgres
    environment:
      POSTGRES_USER: workhub
      POSTGRES_PASSWORD: workhub
      POSTGRES_DB: workhub
    ports:
      - "5432:5432"
    volumes:
      - workhub_postgres:/var/lib/postgresql/data

volumes:
  workhub_postgres:
